/**
 * 
 */
package model;

/**
 * @author MoodyProject Team
 *
 */
public enum EnumWebServices {
	
	CORE_COURSE_CREATE_CATEGORIES,
	CORE_COURSE_CREATE_COURSES,
	CORE_COURSE_DELETE_CATEGORIES,
	CORE_COURSE_GET_CATEGORIES,
	CORE_COURSE_GET_CONTENTS,
	CORE_COURSE_GET_COURSES,
	CORE_COURSE_UPDATE_CATEGORIES,
	CORE_ENROL_GET_ENROLLED_USERS,
	CORE_ENROL_GET_USERS_COURSES,
	CORE_FILES_GET_FILES,
	CORE_FILES_UPLOAD,
	CORE_GROUP_ADD_GROUP_MEMBERS,
	CORE_GROUP_CREATE_GROUPS,
	CORE_GROUP_DELETE_GROUP_MEMBERS,
	CORE_GROUP_DELETE_GROUPS,
	CORE_GROUP_GET_COURSE_GROUPS,
	CORE_GROUP_GET_GROUP_MEMBERS,
	CORE_GROUP_GET_GROUPS,
	CORE_MESSAGE_SEND_INSTANT_MESSAGES,
	CORE_NOTES_CREATE_NOTES,
	CORE_ROLE_ASSIGN_ROLES,
	CORE_ROLE_UNASSIGN_ROLES,
	CORE_USER__GET_USERS_WITH_CAPABILITY,
	CORE_USER_CREATE_USERS,
	CORE_USER_DELETE_USERS,
	CORE_USER_GET_COURSE_USER_PROFILE,
	CORE_USER_GET_USERS,
	CORE_USER_GET_USERS_BY_ID,
	CORE_USER_UPDATE_USERS,
	CORE_WEBSERVICE_GET_SITE_INFO,
	MOD_ASSIGN_GET_ASSIGNMENTS,
	MOD_ASSIGN_GET_GRADES,
	MOD_ASSIGN_GET_SUBMISSIONS,
	MOODLE_COURSE_CREATE_COURSES,
	MOODLE_COURSE_GET_COURSES,
	MOODLE_ENROL_GET_ENROLLED_USERS,
	MOODLE_ENROL_GET_USERS_COURSES,
	MOODLE_FILES_GET_FILES,
	MOODLE_FILES_UPLOAD,
	MOODLE_GROUP_ADD_GROUP_MEMBERS ,
	MOODLE_GROUP_CREATE_GROUPS,
	MOODLE_GROUP_DELETE_GROUP_MEMBERS,
	MOODLE_GROUP_DELETE_GROUPS,
	MOODLE_GROUP_GET_COURSE_GROUPS,
	MOODLE_GROUP_GET_GROUP_MEMBERS,
	MOODLE_GROUP_GET_GROUPS,
	MOODLE_MESSAGE_SEND_INSTANTMESSAGES,
	MOODLE_NOTES_CREATE_NOTES,
	MOODLE_ROLE_ASSIGN,
	MOODLE_ROLE_UNASSIGN,
	MOODLE_USER_CREATE_USERS,
	MOODLE_USER_DELETE_USERS,
	MOODLE_USER_GET_COURSE_PARTICIPANTS_BY_ID,
	MOODLE_USER_GET_USERS_BY_COURSEID,
	MOODLE_USER_GET_USERS_BY_ID,
	MOODLE_USER_UPDATE_USERS,
	MOODLE_WEBSERVICE_GET_SITE_INFO
	
}
